#pragma once
#include "NativeGameplayTags.h"

namespace PJTags
{
    PJABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PJ_Stat_Health);
    PJABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PJ_Stat_Attack);
    PJABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PJ_Stat_Mana);
    PJABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PJ_Effect_Poison);
    PJABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PJ_Ability_Rage);
    PJABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PJ_Cooldown_Rage);
    PJABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PJ_State_Stun);
}
